# Generated by Django 5.2.14 on 2026-06-05 09:43

from django.db import migrations


def set_stock_total_zero(apps, schema_editor):
    Transaction = apps.get_model('transactions', 'Transaction')
    Transaction.objects.filter(transaction_type__in=('stock_in', 'stock_out')).update(total=0)


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_backfill_unit_price'),
    ]

    operations = [
        migrations.RunPython(set_stock_total_zero),
    ]
